import React, { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { StackScreenProps } from '@react-navigation/stack';
import { RootStackParamList, SavedConversation } from '../types';
import { loadConversationLibrary } from '../store/conversationStore';
import { DESIGN, DesignFrame, GlassButton, Orb } from '../components/CoachieDesign';
import { SettingIcon } from '../components/SettingsDesign';
import { FadeIn } from '../components/Motion';
export default function ConversationScreen({navigation,route}:StackScreenProps<RootStackParamList,'Conversation'>) {
 const [conversation,setConversation]=useState<SavedConversation|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useFocusEffect(useCallback(()=>{let active=true;void loadConversationLibrary().then(items=>{if(active){const item=items.find(item=>item.id===route.params.id);setConversation(item||null);if(!item)setError('This conversation is no longer available.');}}).catch(()=>{if(active)setError('Could not load this conversation.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[route.params.id]));
 return <DesignFrame chat><View style={styles.header}><GlassButton label="Back to Home" onPress={()=>navigation.goBack()} style={styles.back}><SettingIcon name="back"/></GlassButton><Text accessibilityRole="header" style={styles.heading}>{conversation?.isSample?'Sample conversation':'Saved conversation'}</Text><View style={{width:44}}/></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.log}>
 {loading?<Text style={styles.meta}>Loading conversation…</Text>:error?<Text style={styles.text}>{error}</Text>:conversation&&<><View style={styles.topic}><Text selectable style={styles.topicText}>{conversation.topic}</Text><Text style={styles.meta}>{conversation.language} · {conversation.voice} · {conversation.status==='completed'?'Completed':'In progress'}</Text></View>{conversation.rounds.map(round=><React.Fragment key={round.roundNumber}><FadeIn style={styles.aiRow}><Orb/><View style={styles.question}><Text style={styles.meta}>Question {round.roundNumber}</Text><Text selectable style={styles.text}>{round.question}</Text></View></FadeIn><FadeIn style={styles.answer}><Text style={styles.meta}>Your answer</Text><Text selectable style={styles.text}>{round.answer}</Text></FadeIn></React.Fragment>)}{!!conversation.currentQuestion&&<View style={styles.aiRow}><Orb/><View style={styles.question}><Text style={styles.meta}>Question {conversation.rounds.length+1}</Text><Text selectable style={styles.text}>{conversation.currentQuestion}</Text></View></View>}{!!conversation.closingMessage&&<View style={styles.feedback}><Text style={[styles.meta,{color:'#FFB083'}]}>Coach feedback</Text><Text selectable style={styles.text}>{conversation.closingMessage}</Text></View>}<Text style={styles.meta}>{conversation.isSample?'Example transcript · No API requests needed':`Saved ${new Date(conversation.updatedAt).toLocaleString()}`}</Text><GlassButton label="Practice this topic again" onPress={()=>navigation.navigate('Home',{topic:conversation.topic})} style={styles.practice}><Text style={styles.topicText}>Practice this topic again</Text></GlassButton></>}
 </ScrollView></DesignFrame>;
}
const styles=StyleSheet.create({header:{padding:20,paddingBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},heading:{fontFamily:DESIGN.medium,fontSize:16,color:'#FFF'},back:{width:44,height:44},log:{padding:20,paddingBottom:40,gap:18},topic:{alignSelf:'flex-end',maxWidth:'90%',borderRadius:24,borderTopRightRadius:6,padding:18,gap:8,backgroundColor:'#8E2E0A'},topicText:{fontFamily:DESIGN.medium,fontSize:15,lineHeight:23,color:'#FFF'},meta:{fontFamily:DESIGN.font,fontSize:12,lineHeight:18,color:'#C4B4A9'},text:{fontFamily:DESIGN.font,fontSize:15,lineHeight:24,color:'#FFF'},aiRow:{flexDirection:'row',gap:10,alignItems:'flex-start'},question:{flex:1,borderRadius:24,borderTopLeftRadius:6,backgroundColor:DESIGN.panel,padding:18,gap:8,borderWidth:1,borderColor:DESIGN.border},answer:{alignSelf:'flex-end',width:'87%',padding:18,gap:8,borderRadius:24,borderTopRightRadius:6,backgroundColor:'rgba(50,31,20,.9)',borderWidth:1,borderColor:'rgba(249,115,22,.25)'},feedback:{padding:20,borderRadius:24,backgroundColor:DESIGN.panel,borderWidth:1,borderColor:DESIGN.border,gap:10},practice:{padding:16,minHeight:52}});
